### ISSUE TITLE
Active pagination button should not be clickable

### ISSUE THREAD

**Issue by Yukaii** [moda-gov-tw/code-gov-tw#3]
# 問題報告

## 描述

點選目前的頁數，會讓該頁數呈現載入狀態

## 重現步驟

請列出重現問題的步驟：

1. 步驟一：點選目前的頁數
2. 步驟二：會讓該頁數呈現載入狀態

## 期望的行為

目前頁數應不可點選，或是

## 發生環境

- 作業系統與版本：macOS
- 瀏覽器與版本 Arc Chromium Engine Version 124.0.6367.92

## 截圖

https://github.com/moda-gov-tw/code-gov-tw/assets/4230968/35bd3483-8efc-4c11-8462-42ec976839c3

**Comment by canyugs** [comment]
感謝回報！ 已於 #18 修復
