### ISSUE TITLE
Project list filter error

### ISSUE THREAD

**Issue by cssf998811** [moda-gov-tw/code-gov-tw#4]
# 問題報告

## 描述

公共程式專案一覽左側篩選異常

## 重現步驟

請列出重現問題的步驟：

1. 步驟一：到https://code.gov.tw/projects/
2. 步驟二：拉到底選擇第二頁
3. 步驟三：選擇左側篩選列表的公共服務通知

## 期望的行為

預期會顯示GOV.UK Notify的資料

## 發生環境

- 作業系統與版本：Windows 10
- 瀏覽器與版本： Chrome 124.0.6367.91

## 截圖

https://github.com/moda-gov-tw/code-gov-tw/assets/62090405/7325805b-d8aa-497b-bc77-39cf3c85892e

**Comment by canyugs** [comment]
您好，感謝問題回報，已經由 #16 修復
